baseURL: https://zippy-creponne-4ae3e0.netlify.app/
languageCode: en-us
title: English Lesson Recaps
#copyright: 

paginate: 5 #Controls number of pages displayed on list pages
summaryLength: 9
# Following required for Hugo to render MD to HTML
markup:
  goldmark:
    renderer:
      unsafe: true

# Menu links via config file
